# Generated by Django 4.2.5 on 2023-09-25 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_shopingkart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopingkart',
            new_name='Shopingcart',
        ),
    ]
