# Generated by Django 4.2.5 on 2023-09-26 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_rename_quantity_quantity_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopingcart',
            new_name='Shoppingcart',
        ),
    ]
