# Generated by Django 4.2.5 on 2023-09-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_shoppingcart_recipe_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol_ingr', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
